name: Playwright Scraper

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run scraper script
        run: npx playwright test tests/linksautomation.spec.ts

      - name: Upload markdown file
        uses: actions/upload-artifact@v4
        with:
          name: combined-articles
          path: combined-articles.md  # change this to whatever your script outputs
