name: Playwright Tests

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Download previous articles.json
        uses: actions/download-artifact@v4
        with:
          name: articles
          path: .

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload updated articles.json
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: articles
          path: articles.json

      - name: Upload Markdown result
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: article-markdown
          path: combined-articles.md  # Update this if your file has a different name
