name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        # add working-directory if your package.json is not in root

      - name: Install Playwright Browsers
        run: npx playwright install
        # add working-directory if your package.json is not in root

      - name: Run Playwright tests
        run: npx playwright test linksautomation.spec.ts
        # add working-directory if your package.json is not in root
